# config.py
MAGIC_INVERSION = 9995551
MAGIC_CONTINUATION = 9995552
MAGIC_GRID = 9995553

SYMBOLS = ['XAUUSDm', 'BTCUSDm', 'ETHUSDm', 'USTECm', 'USOILm', 'EURUSDm', 'GBPUSDm', 'USDJPYm', 'EURGBPm', 'AUDNZDm']
TERMINAL_PATH = r"C:\Program Files\MetaTrader 5 EXNESS - Copy (2)\terminal64.exe"

ATR_PERIOD = 14
ATR_MULT_SL = 2.5
REWARD_MULTIPLIER = 2.0
RISK_PERCENT = 0.01